server:
  port: 8081

spring:
  application:
    name: customer
  datasource:
    username: 'tutorial'
    url: jdbc:postgresql://localhost:5432/customer
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update