eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

microservice:
  payment-service:
    endpoints:
      uri: http://PAYMENT-SERVICE/payment/do-payment
  order-service:
    endpoints:
      uri: http://ORDER-SERVICE/order/book-order
